# https://taskfile.dev

version: '3'

# vars:
#   GREETING: Hello, World!

tasks:
  build dll:
    cmds:
      - go -C 'C:\Users\kociu\github\injector or something\example dll' build -ldflags="-s -w" -o dllmain.dll -buildmode=c-shared dllmain.go 
  build injector [with go]:
    cmds:
      - go -C 'C:\Users\kociu\github\injector or something' build -ldflags="-s -w" -o injector.exe
  build injector [with fyne for windows]:
    cmds:
      - fyne bundle -o bundled.go icon.png
      - fyne package -os windows -icon icon.png
  bundle files for the app:
    cmds:
      - fyne bundle -o bundled.go Icon.png