name: build

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
        #   {name: Kinjector, platform: linux/amd64, os: ubuntu-latest},
          {name: Kinjector, os: windows-latest},
        #   {name: Kinjector, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build windows/amd64
        shell: bash
        run: |
          if [[ ${{ github.ref_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION='0.0.0'
          fi
          VERSION="${VERSION#v}"  # Remove leading 'v' if it exists
          task build VERSION=$VERSION

      # Upload build assets
      - uses: actions/upload-artifact@v4
        with:
          name: Kinjector build ${{runner.os}} ${{matrix.build.name}}
          path: |
            ${{ github.workspace }}/bin/Kinjector.exe
            ${{ github.workspace }}*\bin\*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          files: |
            **/*/Kinjector.exe
          generate_release_notes: true