name: build

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
        #   {name: Kinjector, platform: linux/amd64, os: ubuntu-latest},
          {name: Kinjector, os: windows-latest},
        #   {name: Kinjector, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: Build windows/amd64
        run: |
          if [[ "${GITHUB_REF#v}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            task build VERSION="${GITHUB_REF#v}"
          else
            task build
          fi

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: Kinjector build ${{runner.os}} ${{matrix.build.name}}
          path: |
            ${{ github.workspace }}/bin/Kinjector.exe
            ${{ github.workspace }}*\bin\*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          files: |
            */bin/Kinjector.exe
          generate_release_notes: true